
package com.example.storeui.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-10-10T17:13:54.850+02:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "plantFault", targetNamespace = "http://www.bp.org")
public class PlantFaultMsg extends Exception {

    private com.example.storeui.model.Fault plantFault;

    public PlantFaultMsg() {
        super();
    }

    public PlantFaultMsg(String message) {
        super(message);
    }

    public PlantFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PlantFaultMsg(String message, com.example.storeui.model.Fault hotelFault) {
        super(message);
        this.plantFault = hotelFault;
    }

    public PlantFaultMsg(String message, com.example.storeui.model.Fault plantFault, java.lang.Throwable cause) {
        super(message, cause);
        this.plantFault = plantFault;
    }

    public com.example.storeui.model.Fault getFaultInfo() {
        return this.plantFault;
    }
}
