/*
 * Plants mircro service
 * Micro service to order plants
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.camel.example.springboot.model.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.apache.camel.example.springboot.model.models.PlantsOrderSummary;
/**
 * OrderSummaryResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-24T13:06:11.103188+01:00[Europe/Warsaw]")
public class OrderSummaryResponse {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("paymentCard")
  private PlantsOrderSummary paymentCard = null;

  public OrderSummaryResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrderSummaryResponse paymentCard(PlantsOrderSummary paymentCard) {
    this.paymentCard = paymentCard;
    return this;
  }

   /**
   * Get paymentCard
   * @return paymentCard
  **/
  @Schema(description = "")
  public PlantsOrderSummary getPaymentCard() {
    return paymentCard;
  }

  public void setPaymentCard(PlantsOrderSummary paymentCard) {
    this.paymentCard = paymentCard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderSummaryResponse orderSummaryResponse = (OrderSummaryResponse) o;
    return Objects.equals(this.id, orderSummaryResponse.id) &&
        Objects.equals(this.paymentCard, orderSummaryResponse.paymentCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, paymentCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderSummaryResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
